version: '3.8'

services:
  # Nginx Proxy Manager service
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
      - "81:81"   # NPM Admin UI
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - web

  # FastAPI backend service
  fastapi-backend:
    build:
      context: ./backend
    environment:
      POSTGRES_SERVER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: changethis123
    expose:
      - "8000"   # Internal port for Nginx Proxy Manager
    networks:
      - web

  # React frontend service
  react-frontend:
    build:
      context: ./frontend
    expose:
      - "80:80"
    networks:
      - web

  # PostgreSQL service
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: changethis123
      POSTGRES_DB: app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - web

  # Adminer service
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080" # Adminer interface
    networks:
      - web

networks:
  web:
    driver: bridge

volumes:
  postgres_data:

